services:
  - name: leaked-passwords-api
    github_repo: GoodbyePlanet/leaked-passwords-api
    github_ref: main

  - name: passkey-service
    github_repo: GoodbyePlanet/passkey-service
    github_ref: main

  - name: auth-server
    github_repo: GoodbyePlanet/spring-cg-bff
    github_ref: main
    root: auth-server
    exclude:
      - "**/test/**"
      - "**/target/**"

  - name: gateway
    github_repo: GoodbyePlanet/spring-cg-bff
    github_ref: main
    root: gateway
    exclude:
      - "**/test/**"
      - "**/target/**"

  - name: secure-resource
    github_repo: GoodbyePlanet/spring-cg-bff
    github_ref: main
    root: secure-resource
    exclude:
      - "**/test/**"
      - "**/target/**"

  - name: spring-cg-bff
    github_repo: GoodbyePlanet/spring-cg-bff
    github_ref: main
    exclude:
      - "auth-server/**"
      - "gateway/**"
      - "secure-resource/**"
      - "fe-client/**"

  - name: fe-client
    github_repo: GoodbyePlanet/spring-cg-bff
    github_ref: main
    root: fe-client
    exclude:
      - "**/node_modules/**"
